services:
 db:
  image: postgres:16-alpines 
  container_name: 69-s2-postgres
  ports:
    -54321:5432
  environment:
    -POSTGRES_PASSWORD=arm1234
    -POSTGRES_USER=phanuvit
    -POSTGRES_DB=phanuvit
