services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: arm1234
      POSTGRES_USER: phanuvit
      POSTGRES_DB: phanuvit

  admin:
    image: dpage/pgadmin4
    container_name: 69-s2-admin
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: arm123
    depends_on:
      - db
      
